root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - jest
extends:
  - eslint:recommended
  # react, react-hooks, next plugin is included in eslint-config-next
  - next/core-web-vitals
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - prettier
env:
  browser: true
  jest: true
