arrowParens: avoid
bracketSameLine: true
bracketSpacing: true
embeddedLanguageFormatting: auto
htmlWhitespaceSensitivity: css
insertPragma: false
jsxSingleQuote: false
printWidth: 80
proseWrap: preserve
quoteProps: consistent
requirePragma: false
semi: false
singleAttributePerLine: false
singleQuote: true
tabWidth: 2
trailingComma: none
useTabs: false
vueIndentScriptAndStyle: false
